### ISSUE TITLE
Release etsdemo 0.1.0

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1031]
This issue is for releasing the `etsdemo` distribution sitting in this repository's `ets-demo` folder.

This is the first release of etsdemo. Future release process may differ.

Pre-release
------------
- [x] Check metadata in `setup.py` is good, e.g. `url`, `download_url`, `package_data` are correct (#1111)
- [x] Check MANIFEST.in is up-to-date: Build a source distribution and see if it captures the files we want to distribute (#1117)
- [x] Prepare Changelog, open a PR against master (#1109)

Release
--------
- [x] Create a release branch `etsdemo/release/0.1.x`, push to GitHub
- [x] From the master branch, bump the release version to 0.2.0 for the development of the next release, create a PR to target master (#1119)
- [x] Create a new branch from the release branch, set IS_RELEASED flag to True, commit. Open a PR targeting `etsdemo/release/0.1.x` (#1120)
- [x] On the commit where IS_RELEASED is true, tag `git tag -a etsdemo/0.1.0 -m "REL: Release of etsdemo 0.1.0"`. Double check the tag with `git show etsdemo/0.1.0`. Push the tag to GitHub `git push origin etsdemo/0.1.0`.
- [x] Checkout the release commit. Do a `git clean -ffxd` in case. Build a source distribution. Install from source distribution and run tests in a work directory that is out of source.
- [x] Upload to PyPI
- [x] Test the PyPI package

Post-release
-------------
- [x] Request an egg be built for EDM `enthought/free` repo.
- [x] Announcement

Note for future reference: The distribution is currently quite basic. The README already contains all the documentation necessary. Should it need to grow in the future, we may need separate documentation and additional steps for publishing the documentation.

**Comment by kitchoi** [comment]
All done. Closing.
