### ISSUE TITLE
Pre-release checklist for UITester

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1173]
Currently the UITester is being developed and tested with TraitsUI's own test suite. Eventually when the API is mature enough, it will need to be made public. There are a number of tasks that need to be evaluated before that. Collecting them here as a reminder and for discussion. Feel free to expand and open separate issues for them if needed.

- [x] Evaluate naming of modules / classes / functions
       - Rename modules (#1248)
       - Rename `UIWrapper.target` (#1249)
- [x] Add `traitsui.testing.api` to expose API components. This also serves as a facade. (#1269)
- [x] Documentation in the user manual with an example for writing an integration test (#1223)
- [x] Move pushing trait change exception handler out. (#1232)
- [x] Update demo examples to import from `traitsui.testing.api` instead (#1274)
- [x] Rename TargetRegister.register_handler and register_solver #1273

**Comment by rahulporuri** [comment]
Regarding naming of modules, do we really need the additional `implementation` submodule under qt4/wx in the tester?

- https://github.com/enthought/traitsui/tree/master/traitsui/testing/tester/wx/implementation
- https://github.com/enthought/traitsui/tree/master/traitsui/testing/tester/qt4/implementation

**Comment by kitchoi** [comment]
We could rename `implementation` to `editors`. I think everything in there are editor domain specific, and everything outside but still within the `qt4` / `wx` namespace are not editor specific but still toolkit specific. Then again, we could also remove that separation. Whichever way to help understanding the structure and to help making the location of new code obvious is good.

**Comment by kitchoi** [comment]
Another renaming to be considered:
- `TargetRegistry.register_solver` -> `TargetRegistry.register_location`
- `TargetRegistry.register_handler` -> `TargetRegistry.register_interaction`

**Comment by aaronayres35** [comment]
The last bullet was completed by PR #1275.  Closing now
