### ISSUE TITLE
TraitsUI Bugfix Release 7.0.1

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#933]
Target date: To be confirmed, will edit here once confirmed.

This is a bug fix release and therefore the procedure will be slightly different compared to a major/minor release.
See https://github.com/enthought/pyface/issues/557 for Pyface release 7.0.1

Pre-release
---
- [x] Verify PRs that need to be merged to the maintanence branch are included in the Release 7.0.1 milestone
- [x] Cherry pick these PRs onto the `fix/7.0.1-bugfixes` branch (see #800)
- [x] Review #800 and merge it to `maint/7.0` branch
- [x] Test against other ETS packages and other traitsui-using projects
- [x] Update changelog and open PR targeting `maint/7.0` branch (#976)
- [x] Check MANIFEST and requirements are still up to date.
- [x] Test building the documentation

Release
-------
- [x] Create PR targeting `maint/7.0` branch. In this PR: (#1003)
        - Set release to `7.0.1`, and set `IS_RELEASED` is true; commit
        - Bump the version to `7.0.2` and set `IS_RELEASED` to false; commit
- [x] On the release commit (where `IS_RELEASED` is true), add an annotated tag, and push the tag
- [x] Make PR targeting `gh-pages` branch: Generate documentation and copy the content to the branch. Verify that the resulting docs/index.html looks good. See https://github.com/enthought/traitsui/pull/787 for a similar PR (#1004)
- [x] Install from source distribution and run tests again
- [x] Upload to PyPI
- [x] Test the PyPI package
- [x] Announcement

Post-release
-------------
- [x] Package update for `enthought/free` repository (for EDM)
- [x] Backport release note and change log to master, and possibly `maint/7.0` branch (#1006)

**Comment by kitchoi** [comment]
Note: The steps need to be updated so that the release commit (with `IS_RELEASED` is true) is on the maintenance branch `maint/7.0`

**Comment by rahulporuri** [comment]
closing as all of the items on the release checklist are complete
